name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs rsync
          git lfs install

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git clone https://alifya:${HF_TOKEN}@huggingface.co/spaces/alifya/mineral_classification_demo hf_space

          rsync -av --delete \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "hf_space" \
            app.py README.md requirements.txt mineral_classifier configs models hf_space/

          cd hf_space

          git lfs track "*.pt"
          git add .gitattributes
          git add .

          git commit -m "Deploy mineral classification app" || echo "No changes to commit"

          git push origin main
